services:

  eureka-1:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    image: discovery-service:1.0.0
    container_name: eureka-1
    hostname: eureka-1
    restart: unless-stopped
    #ports:
    #  - "8761:8761"
    env_file:
      - global.env
      - ./discovery-service/discovery-service-1.env
    networks:
      - pharmaflow-net
    volumes:
      - /app/logs/discovery-service:/app/logs/discovery-service

  eureka-2:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    image: discovery-service:1.0.0
    container_name: eureka-2
    hostname: eureka-2
    restart: unless-stopped
    #ports:
    #  - "8762:8762"
    env_file:
      - global.env
      - ./discovery-service/discovery-service-2.env
    networks:
      - pharmaflow-net
    volumes:
      - /app/logs/discovery-service:/app/logs/discovery-service

  eureka-3:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    image: discovery-service:1.0.0
    container_name: eureka-3
    hostname: eureka-3
    restart: unless-stopped
    #ports:
    #  - "8763:8763"
    env_file:
      - global.env
      - ./discovery-service/discovery-service-3.env
    networks:
      - pharmaflow-net
    volumes:
      - /app/logs/discovery-service:/app/logs/discovery-service

  gateway-1:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:1.0.0
    container_name: gateway-1
    hostname: gateway-1
    restart: unless-stopped
    depends_on:
      - eureka-1
      - eureka-2
      - eureka-3
    ports:
      - "8091:8091"
    env_file:
      - global.env
      - ./api-gateway/api-gateway-1.env
    networks:
      - pharmaflow-net
    volumes:
      - /app/logs/api-gateway:/app/logs/api-gateway

  gateway-2:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:1.0.0
    container_name: gateway-2
    hostname: gateway-2
    restart: unless-stopped
    depends_on:
      - eureka-1
      - eureka-2
      - eureka-3
    ports:
      - "8092:8092"
    env_file:
      - global.env
      - ./api-gateway/api-gateway-2.env
    networks:
      - pharmaflow-net
    volumes:
      - /app/logs/api-gateway:/app/logs/api-gateway

  auth-1:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: auth-service:1.0.0
    container_name: auth-1
    hostname: auth-1
    restart: unless-stopped
    depends_on:
      - eureka-1
      - eureka-2
      - eureka-3
    env_file:
      - global.env
      - ./auth-service/auth-service-1.env
    #extra_hosts:
    #  - "host.docker.internal:host-gateway" # Habilitar solo para BD local
    networks:
      - pharmaflow-net
    volumes:
      - /app/logs/auth-service:/app/logs/auth-service

networks:
  pharmaflow-net:
    driver: bridge
